# 📝 NumPy Test – MCA 1st Year

**Instructions:**
- Solve all questions using NumPy.
- Write clean and readable code.
- Avoid explicit Python loops unless necessary.
- Each question carries equal marks.


## Import Required Library

In [2]:
import numpy as np

## Question 1
Create a NumPy array containing numbers from **1 to 20**.
- Print the array
- Print its **shape, size, and data type**

In [3]:
arr = np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20]])
               
print(np.size(arr))
print(np.shape(arr))
print(type(arr))

20
(4, 5)
<class 'numpy.ndarray'>


## Question 2
Create a **5 × 5 matrix** containing numbers from **1 to 25** using NumPy.
- Extract the **third row**
- Extract the **last column**

In [7]:
arr1 = np.arange(1,26).reshape(5,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Question 3
Generate **10 random integers between 10 and 100**.
- Print the array
- Find the **maximum, minimum, and mean** value.

In [22]:
random = np.random.randint(10,101,10)
print(np.max(random))
print(np.min(random))
print(np.mean(random))

92
12
48.7


## Question 4
Create two arrays:
```
a = [1,2,3,4,5]
b = [6,7,8,9,10]
```
Perform the following operations:
- Addition
- Multiplication
- Square of array `a`

In [14]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a+b
d = a*b
print(c)
print(d)
np.sqrt(a)

[ 7  9 11 13 15]
[ 6 14 24 36 50]


array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

## Question 5
Create an array containing numbers from **1 to 50**.
- Extract all **even numbers** using NumPy operations.

In [21]:
arr3 = np.arange(1,51)
arr3[1::2]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

## Question 6
Generate an array of **15 random numbers between 1 and 100**.
- Find numbers **greater than 60** using Boolean masking.

In [26]:
arr4 = np.random.randint(1,101,15)
print(arr4)
x = arr4[arr4>60]
print(x)

[95 99 14 15 98 19 95 22 65 48 77 51 91 77 40]
[95 99 98 95 65 77 91 77]


## Question 7
Create the following 3×3 matrix:

```
1 2 3
4 5 6
7 8 9
```

- Calculate **sum of each row**
- Calculate **sum of each column**

In [28]:
arr5 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
c =np.sum(arr5,axis =0)
r =np.sum(arr5,axis =1)
print(r)
print(c)

[ 6 15 24]
[12 15 18]


## Question 8 (Application Based)
Generate marks for **30 students** using random numbers between **30 and 100**.

Perform the following:
- Calculate the **average marks**
- Find the number of students **scoring above average**
- Add **5 grace marks** to every student using vectorized operation.

In [35]:
a = np.random.randint(30,100,30)
avg = np.mean(a)
print(avg)
above_avg = a[a>avg]
print(above_avg)
print(a+5)


59.6
[97 96 63 83 68 86 64 72 63 79 60 96 92 87 62]
[ 40  55  35  44 102 101  55  46  68  61  40  88  35  73  45  48  91  69
  43  77  42  46  68  84  65 101  97  60  92  67]
